### ISSUE TITLE
Investigate Yarn to reduce memory footprint

### ISSUE THREAD

**Issue by mkovatsc** [eclipse/thingweb.node-wot#15]
Copied from https://github.com/thingweb/node-wot/issues/57

A node-wot development installation takes more than 500 MiB because of the node_modules copies. Would be nice to reduce this footprint for less powerful devices such as old Raspberry Pis, Edisons, etc.

TODO:
* Create a target `production` with something like `sudo lerna exec -- npm prune --production`
* Try out https://yarnpkg.com/

**Comment by h0ru5** [comment]
Can confirm `yarn` works fine with this, problem is: some scripts call npm explicitly

**Comment by wiresio** [comment]
I tried:
-	yarn init
-	yarn add [packages]
-	npm run build
-	lerna exec 'npm prune --production'
and checked functionality by running the counter.js example - which worked. The size of compiled node-wot w/ all packages was reduced from 786 MByte down to 182 MByte.
A TODO would now be to add a respective rule to package.json.

**Comment by h0ru5** [comment]
@wiresio not necessary.
you can also just reuse the existing package.json (and npm lockfiles to be correct).
just remove the existing `node_modules` and run `yarn` (== `npm install`) and you will have the modules.

Also instead of running `npm run build` you can run `yarn build` (works for all scripts in package.json)

downside of yarn is, its one more step to install and document and AFAIK there is no equivalent for  `npx` (running locally installed tools from `./node_modules/.bin/`)

I am not sure how lerna does work with yarn however...

**Comment by danielpeintner** [comment]
Mhh, I tried the following 

0. removed all `node_modules` folders  etc
1. Installed yarn
2. run `yarn`
3. run `yarn build`

and I was back at 700MB :-(

**Comment by wiresio** [comment]
This is also my experience. That's why 'pruning' is necessary to reduce the size. When you prune without having run yarn before, node-wot will not work.

**Comment by h0ru5** [comment]
ahh, ok. 
I guess that's b/c of prod vs. dev.
https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-production-true-false

try `yarn --production` instead or set env variable `NODE_ENV=production` (probably only latter one will work with lerna)

above, you install devDeps with yarn, then prune them away with npm, leaving only prod.

the same is for npm by the way: https://docs.npmjs.com/cli/install

**Comment by h0ru5** [comment]
Ok, seems installing & pruning is the right way here, because lerna has an issue regarding production flags:
https://github.com/lerna/lerna/issues/721
