### ISSUE TITLE
How to import utils script from the same folder of WoT script?

### ISSUE THREAD

**Issue by philiptran** [eclipse/thingweb.node-wot#191]
We need to import some utility script from the same folder of WoT script using the `require` function. But the local script file can not be resolved correctly.

## To reproduce

The counter.js is copied to a separate folder and to be run using @node-wot CLI as `As a Node.js dependency` mode.

1. Create config.js file in the same folder of the WoT script with the following content:

```
const config = {
    API_URL: 'https://localhost/api/',
    API_AUTHORIZATION: 'xyz'
};
module.exports = config;
```

1. Edit counter.js to add the following:

```
const config = require("./config");
```

1. Run the `counter.js` script using @node-wot CLI, the following error is thrown.

```
Servient caught error in privileged 'C:\wot\counter.js' and halted with internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module './config'
Require stack:
...
```

**Comment by philiptran** [comment]
A workaround is to import the `config.js` as follow.

```
const path = require('path');
const config = require(path.resolve('./config'));
```

**Comment by egekorkan** [comment]
For similar issues I had before, this is due to the fact that CLI runs the script but the directory it uses is actually its own. You can run process.cwd() to understand where it is running from.

Another workaround would be specifying the full path but this is a dirty solution.
Could you try to use the scriptDir option? (I am not very sure about it though)
```json
{
    "servient": {
        "scriptDir": AUTORUN,
        "scriptAction": RUNSCRIPT
    }
}
```
  AUTORUN is a path string for the directory to load at startup
  RUNSCRIPT is a boolean indicating whether to provide the 'runScript' Action

**Comment by philiptran** [comment]
Yes, it was trying to run `process.cwd()` to figure out the current working directory but the `process` object is not exported to WoT script hence I did the workaround using `path.resolve` as above. 

Please see issue #190 for issue with `process` object.

**Comment by danielpeintner** [comment]
@relu91 solved by https://github.com/eclipse/thingweb.node-wot/pull/315 ?

**Comment by relu91** [comment]
Just tested, yes solved!
