### ISSUE TITLE
subscribe() for ConsumedThingProperty

### ISSUE THREAD

**Issue by mkovatsc** [eclipse/thingweb.node-wot#21]
Needs to be implemented...
`ExposedThingProperty` needs a `Subject` and `next()` calls.

**Comment by mkovatsc** [comment]
For now at least a placeholder that provides a meaningful error ("not implemented").

**Comment by alexbrdn** [comment]
It seems to me that `subscribe()` did [get implemented](https://github.com/eclipse/thingweb.node-wot/blob/master/packages/core/src/consumed-thing.ts#L243) in the meantime, but it fails to work with coaps (I'm using good old Trådfri lamps).

Here's what I was able to figure out: [`ContentSerdes.contentToValue()`](https://github.com/eclipse/thingweb.node-wot/blob/master/packages/core/src/content-serdes.ts#L114) expects the `content` to have field `body`. [`read`](https://github.com/eclipse/thingweb.node-wot/blob/master/packages/binding-coap/src/coaps-client.ts#L51) and [`invoke`](https://github.com/eclipse/thingweb.node-wot/blob/master/packages/binding-coap/src/coaps-client.ts#L79) do provide `content.body` to the callback. However, [`subscribe`](https://github.com/eclipse/thingweb.node-wot/blob/master/packages/binding-coap/src/coaps-client.ts#L97) calls `coaps.observe()`, which results in the response message from [`CoapClient`](https://github.com/AlCalzone/node-coap-client/blob/master/src/CoapClient.ts#L773) to be sent directly to `next` callback, bypassing the conversion as in `read` and `invoke`.

Result: Parsing error at [`codec.bytesToValue()`](https://github.com/eclipse/thingweb.node-wot/blob/master/packages/core/src/content-serdes.ts#L114), because `content.body` is undefined.

The fix for coaps is simple enough, but I don't know how well it will play with all other bindings, hence no PR.

**Comment by sebastiankb** [comment]
quick question: which node-wot version are you using?

**Comment by alexbrdn** [comment]
* 7ff8cdd (HEAD, tag: v0.6.2) chore: update version tag for 0.6.2 node-wot release

**Comment by danielpeintner** [comment]
Is this issue still unresolved even after the *new* Scripting API changes/updates?

**Comment by danielpeintner** [comment]
HTTP is fixed by https://github.com/eclipse/thingweb.node-wot/pull/233 while CoAP has been fixed before.

Please reopen if you encounter any related issue.
