### ISSUE TITLE
Error in coap-servient example

### ISSUE THREAD

**Issue by fcapello** [eclipse/thingweb.node-wot#26]
Running the coap-servient example provided produces an error:
> Unexpected token t in JSON at position 2

adding double quotes to `type` (lines with `{ type: "string" }`) resolves it. 

Its probably due to the way ExposedThing handles the schemas.

**Comment by mkovatsc** [comment]
Note that this example is to illustrate how to use node-wot as library (from NPM) to build your own Servient.

The problem is that this example, to work straight-forward, requires published node-wot modules on NPM. As they are intrinsicly under development, though, this example does not work in development phases.

To develop you own Servient on development code, it makes much more sense to extend the demo-servients package, as here the development snapshots are linked via lerna.

**Comment by danielpeintner** [comment]
@fcapello @mkovatsc I believe this issue has been solved by now. correct?

**Comment by danielpeintner** [comment]
no reply -> close
