### ISSUE TITLE
Are W3C Web Thing Model operations supported by Thingweb?

### ISSUE THREAD

**Issue by Emiltzav** [eclipse/thingweb.node-wot#279]
Hello everyone! I'm very interested in this work and I would like to ask if it supports all the operations proposed by W3C Web Thing Model (described here: https://www.w3.org/Submission/wot-model), e.g. **Retrieve a Web Thing**, **Update a Web Thing**, etc. From what I have seen so far, Thingweb supports all the basic operations and interactions with a Web Thing, but could someone please indicate to me **which exactly operations** of Web Thing Model are supported by Thingweb until now? For instance, if I'm not mistaken, the operation "Retrieve recent executions of a specific action" may not be supported in this project so far. I may be wrong about that. 

Thank you in advance!

**Comment by egekorkan** [comment]
Hi @Emiltzav, thank you for your interest in this work! The page you wanted to link does not appear but if you are talking about the W3C WoT Architecture which lists the possible operations (https://w3c.github.io/wot-architecture/#sec-hypermedia-forms), they are mostly supported. The support depends on the concrete protocol. For example, we have `readproperty` in HTTP but not in MQTT since it was not implementable until recently with MQTT 5.0. To check which ones are implemented in each protocol, I think for now you have to check the README.md of each protocol binding. We are working on making it more visible at https://github.com/eclipse/thingweb.node-wot/issues/213.

However, if you are talking about one of the following, we do not support them since they are not W3C standards:
- https://www.w3.org/Submission/wot-model/
- https://www.w3.org/blog/wotig/2017/01/13/web-thing-model-member-submission/

I have linked those two ,since in the working group of W3C, we do not refer to anything as W3C Web Thing Model.

**Comment by egekorkan** [comment]
Sorry, I didn't see the edit even though you edited before I commented but I think addressed it :)

**Comment by Emiltzav** [comment]
Hi @egekorkan ! Thank you for your immediate response! Indeed you addressed it, but still I'm a little confused because I had the impression that you did support Web Thing Model ( https://www.w3.org/Submission/wot-model/ ). That's because, while watching your node-wot tutorial on youtube and running the examples of the project, I realized that some operations of the model like "Retrieve a Web Thing model", "Update a specific property" or "Execute an action" (and some more) are actually supported by your work, although it does not always follow the suggested (by Web Thing Model) endpoints or JSON response payloads. Moreover, it seems that Web Thing Model's operations are very similar to the ones that you indicate in your comment above, in _Table 1 Well-known Operation Types for the Web of Things_ ( https://w3c.github.io/wot-architecture/#sec-hypermedia-forms ), _e.g. writeproperty, readallproperties, writemultipleproperties, invokeaction, etc_. So could we say that Thingweb **partly supports** this model (i.e. not every operation of the model)?

**Comment by egekorkan** [comment]
I would not want to make any claims myself but inofficially we can say that it has a similar point of view :) For example, in Web Thing Model there is a statement like "By default, all PUT, POST, and DELETE requests to a Web Thing should not return the payload of the object that was created/modified, therefore should return a 204 NO CONTENT response and no response body. " (
https://www.w3.org/Submission/wot-model/#r1.4-a-web-thing-should-return-a-204-for-all-write-operations). We don't have such statements for example and will not have them either. The goal of TDs is to describe what is already existing.

**Comment by Emiltzav** [comment]
Thank you very much, @egekorkan ! I think it is clear to me now.

**Comment by egekorkan** [comment]
No problem! :) @danielpeintner or @Emiltzav , the issue can be closed now
