### ISSUE TITLE
How to update protocol interface for revised scripting API

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#382]
The latest scripting API (see https://www.w3.org/TR/wot-scripting-api/) reports for  [`readProperty()`](https://www.w3.org/TR/wot-scripting-api/#the-readproperty-method) for example an [`InteractionOutput`](https://www.w3.org/TR/wot-scripting-api/#dom-interactionoutput):

```
interface InteractionOutput {
        data?: ReadableStream;
        dataUsed: boolean;
        form?: Form;
        schema?: DataSchema;
        arrayBuffer(): Promise<ArrayBuffer>;
        value(): Promise<any>;
    }
```

The current [protocol interface](https://github.com/eclipse/thingweb.node-wot/blob/master/packages/core/src/protocol-interfaces.ts) in node-wot is rather simple returning `Content`:

```
interface Content {
  type: string,
  body: Buffer
}
```

What do people think is the best way to evolve the `Content` interface?
@relu91 @egekorkan all ?

**Comment by relu91** [comment]
please assign to me to this issue I'll try to propose an implementation for the end of this week!

**Comment by danielpeintner** [comment]
Thanks @relu91 for volunteering!
I might propose to first _sketch_ the idea/proposal to keep the initial work load lower. What do you think?

**Comment by relu91** [comment]
> I might propose to first sketch the idea/proposal to keep the initial work load lower. What do you think?

Sure! thank you.

**Comment by danielpeintner** [comment]
@relu91 proposed the following change in PR https://github.com/eclipse/thingweb.node-wot/pull/384
changing `body: Buffer` to `body: NodeJS.ReadableStream`

```
interface Content {
  type: string,
  body: NodeJS.ReadableStream;
}
```

I am not 100% sure about the difference between `ReadableStream` and `NodeJS.ReadableStream` or the associated consequences.
@relu91 can you explain it a bit.. thanks!

One thought that comes to my mind when a I see this revised interface for `Content` that goes back and forth from node-wot `core` to `bindings` is that we do **not** make  use of the more sophisticated `InteractionOutput` interface. That raises the question whether we actual need that or whether we could live purely with stream in the scripting API also. Do you see what I mean?

@egekorkan do you have any input?

**Comment by relu91** [comment]
> I am not 100% sure about the difference between ReadableStream and NodeJS.ReadableStream or the associated consequences.
@relu91 can you explain it a bit.. thanks!

With the types installed in node-wot ReadableStream is a Stream as defined in the [Web platform](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream) whereas the [NodeJS.ReadableStream](https://nodejs.org/api/stream.html#stream_readable_streams) is the Nodejs variant. Their methods differ quite a lot but luckily I've found a  [library](https://www.npmjs.com/package/web-streams-polyfill) that is able to convert a NodeJS,ReadableStream back to the web version. We need the Web variant because in the Scripting API we define data as instance of [ReadableStream](https://www.w3.org/TR/wot-scripting-api/#dom-interactionoutput-data). The biggest consequence here is that we are adding web-streams-polyfill which is about 7 Mb to the core package. I would have preferred a more lightweight solution... mostly because the library defines other packages that we don't need. We might use some tree-shaker to reduce our final package size. 

> One thought that comes to my mind when a I see this revised interface for Content that goes back and forth from node-wot core to bindings is that we do not make use of the more sophisticated InteractionOutput interface. That raises the question whether we actual need that or whether we could live purely with stream in the scripting API also. Do you see what I mean?

This is a good discussion point. We could completely remove the Content indeed and use InteractionInput and InteractionOutput objects also at the binding level (if I'm correctly reading your idea). The point is that most of the current implementations just don't care about streams (the only HTTP is optimized in this sense) and uses simply buffers and the type field. If we are going to change this interface we may risk dealing with a lot of changes in every binding implementation.

Another point is that currently it is just an interface and I had to define the helpers method to convert Buffers to Streams and vice-versa in a dedicated utility class. I think it may be good to factor every function inside a possible Content class. On the other hand, having a lean interface reduces the requirements for the protocol implementation.

**Comment by danielpeintner** [comment]
@egekorkan @sebastiankb @wiresio  do you have an opinion?

**Comment by sebastiankb** [comment]
Personally, I love the beauty of this one liner
```js
const jsonValue = await thing.readProperty("temperature")
```  

With the new interface, this will no longer be straightforward and gets more complex:

```js
const jsonValue = (await (await thing.readProperty("temperature")).value());
```  

Or you have to go for a two liner for better readability:

```js
const response = await thing.readProperty("temperature"));
const jsonValue = await response.value();
```  

I see the advantage of the new approach but I'm wondering if there is a kind of hybrid approach possible?

**Comment by relu91** [comment]
Thanks for the feedback @sebastiankb we should strive to have the cleanest solution. Of course, we have quite a few options to get closer to what you're expecting. I suggest moving the discussion to the Scripting API repository since the original issue was more about the interface between the servient and the protocol bindings whereas you are referring to the interface between scripts and applications. 

I opened the following issue: 

https://github.com/w3c/wot-scripting-api/issues/306

**Comment by danielpeintner** [comment]
Changes from [master](https://github.com/eclipse/thingweb.node-wot/blob/master/packages/core/src/protocol-interfaces.ts) to [v0.8.x](https://github.com/eclipse/thingweb.node-wot/blob/v0.8.x/packages/core/src/protocol-interfaces.ts) are done...

Question:  Do we expect (plan?) more changes for the v0.8.x API? If so we ought to do the changes soon.. before kicking of new work? Any opinions?

**Comment by relu91** [comment]
Hi @danielpeintner we started to bring also `InteractionInput` in 0.8.x branch. Currently we are working [here](https://github.com/relu91/thingweb.node-wot/pull/7), I'll submit a PR ASAP

**Comment by danielpeintner** [comment]
The changes **I** meant were purely related to `protocol-interfaces.ts` which affects other bindings..

the changes there are limited to the following and are meant to stay, right? 

![grafik](https://user-images.githubusercontent.com/11281461/124093774-72077280-da58-11eb-8283-179f5481e5e5.png)

**Comment by relu91** [comment]
> the changes there are limited to the following and are meant to stay, right?

I would say yes. I was wondering if we can define a more convenient way to handle Content instances. For example, having a full-blown Content class would mean to have a method dedicated to the conversion of the content stream (body) to a Buffer (i.e., the current `ProtocolHelper.readStreamFully`). However functional people would prefer the current design. Notice that this is internal to node-wot architecture (i.e., how core interacts with protocol bindings implementations) and it does not mess with the public APIs. 

The thing that is meant to stay is the fact that bindings should deal with streams from now on.

**Comment by danielpeintner** [comment]
The statements make sense 👍 

Related: the API might change w.r.t. destroy a thing (see https://github.com/eclipse/thingweb.node-wot/issues/431) but this is somewhat unrelated

**Comment by relu91** [comment]
Content interface is becoming stable. Once we close the implementation for ExposedThing, we might close this issue.

**Comment by danielpeintner** [comment]
I think this issue can be closed by now.
