### ISSUE TITLE
Handling Thing Models

### ISSUE THREAD

**Issue by egekorkan** [eclipse/thingweb.node-wot#426]
a TM/Partial TD that is passed into the produce method can contain `"@type":"tm:ThingModel"`. This should be however removed when the TD is produced as mentioned by @relu91 at 

>The tm:ThingModel value of the top-level @type MUST to be replaced by the value Thing in the Partial TD instance.

Also, theoritically, this should happen when the expose method is called, I think. Also, what is passed into produce does not have to contain `@type` keyword or it can contain but its value can contain something else, like `saref:Sensor`. 
Nothing difficult but a simple replacement without some if checks will result in wrong behavior.

**Comment by danielpeintner** [comment]
Yes, the place might be close to 

https://github.com/eclipse/thingweb.node-wot/blob/5ffd659a2502657151ad4927dacab3849a09a060/packages/core/src/wot-impl.ts#L89-L90

**Comment by danielpeintner** [comment]
https://github.com/eclipse/thingweb.node-wot/pull/429/commits/1f7bdde1000eeb3f778b7a0a96564ec3143c0a43 should fix the issue for the upcoming API.

We still have v.07.x .. I guess we need to change it there also.. it gets now more complicated to keep up several branches...

**Comment by danielpeintner** [comment]
Note: `@type` can be an array, so this should be handled also

**Comment by relu91** [comment]
Thanks, Ege for posting the issue! Although the suggestion would improve the situation I am afraid is not the final solution to handle TMs. If we allow TMs in the `produce` method this means that it should be also able to handle tm:ref and tm:extend right? We discussed having full support for TMs in `produce` function in the Scripting API call but the final agreement was that TMs should be first pre-processed by **external-service** and then passed to the produce. 

See the long discussion here: https://github.com/w3c/wot-scripting-api/issues/304

**Comment by egekorkan** [comment]
Well I agree with this that this is what should be done but nothing stops a person from entering a TM into the produce method. One solution would be to detect this and fail early saying that this is not allowed. node-wot should not generate invalid TDs no matter what in my opinion

**Comment by relu91** [comment]
> Well I agree with this that this is what should be done but nothing stops a person from entering a TM into the produce method. One solution would be to detect this and fail early saying that this is not allowed. node-wot should not generate invalid TDs no matter what in my opinion

Ok, but in your proposal, you are saying to fail _silently_ and just remove the `tm:ThingModel`.  Anyhow, the current trend in the `produce` method is to fail silently so yeah, it might make sense to go on down that path. It feels a little bit too much an ad hoc workaround but I can live with that. Should we remove also other TM related keywords: `tm:ref` and `tm:extends` ?

**Comment by egekorkan** [comment]
> Should we remove also other TM related keywords: tm:ref and tm:extends ? 

I would say so. 

Regarding failing silently, I prefer when there is nothing silent :D

**Comment by egekorkan** [comment]
Also another point, how can we still keep the TM passed into produce and then link to it back via links and rel:type mechanism? It would be nice if the TMs can be still hosted by the servient

**Comment by danielpeintner** [comment]
I agree, it would be _ideal_ to have a way to pass in an object to `produce()` and get an error back in case something is wrong.... but I think since the input to `produce()` can be essentially anything this is hard to achieve...

I see 2 steps here
1. create an _external_ method (helper function) that takes a TM and creates a valid partial TD
2. prune TM related keywords like  `"@type":"tm:ThingModel"`, `tm:ref` and `tm:extends` 

Honestly, I am not so sure about step 2. Shouldn't we trust the user to do the right thing by passing a partialTD to `produce()`?

**Comment by egekorkan** [comment]
I would say that option 1 should exist anyways but in my opinion TDs produced by node-wot should always be valid. node-wot already does some processing of the TD passed into the `produce()` so it would be easy for the user to assume that TM related stuff are also processed and sanitized. For example, I can put a TD without `id` and it is put automatically since at some point, `id` was mandatory or how `@context` is put now. These are things that can be done via the user but security related keys will be always generated by node-wot. In other words, we already do not trust the user :D

**Comment by relu91** [comment]
> Regarding failing silently, I prefer when there is nothing silent :D

> I agree, it would be ideal to have a way to pass in an object to produce() and get an error back in case something is wrong.... but I think since the input to produce() can be essentially anything this is hard to achieve...
>
>I see 2 steps here
>
> create an external method (helper function) that takes a TM and creates a valid partial TD
prune TM related keywords like "@type":"tm:ThingModel", tm:ref and tm:extends
Honestly, I am not so sure about step 2. Shouldn't we trust the user to do the right thing by passing a partialTD to produce()?

So I just checked the new algorithm that we defined for the `produce` method. It seems that the new version can indeed fail and throw an exception if the `init` object does not satisfy the partial td validation (see https://w3c.github.io/wot-scripting-api/#expand-an-exposedthinginit). In this sense, we already agreed to move from "silence" to "loud errors" 🤣 . I kinda hate to say this but it feels that the best way to solve this issue is to move the implementation to the `0.8.x` branch and fully follow the new specs. We could even improve the specs describing this situation (if it is not already covered by json schema validation)

**Comment by danielpeintner** [comment]
> Edit: I've just checked @danielpeintner 's PR and it is actually already for the 0.8.x which is great. So my opinion would be to implement a full JSON schema validation there and do these additional checks -> throw if something is off.

+1

I agree. For 0.8.x we planned to introduce [AJV](https://github.com/eclipse/thingweb.node-wot/issues?q=is%3Aissue+is%3Aopen+validation+label%3AAJV) dependency already..

**Comment by egekorkan** [comment]
I agree with all the points above as well :)
