### ISSUE TITLE
CoAP Client not fully working

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#522]
using the counter sample shows the following errors for the CoAP client portion

```
Script error: TypeError: Cannot read property 'body' of undefined
    at C:\Projects\WoT\thingweb\thingweb.node\packages\binding-coap\dist\coap-client.js:56:60
```

Work should be started after merging https://github.com/eclipse/thingweb.node-wot/pull/513 since it fixed some other parts.

**Comment by JKRhb** [comment]
I am not sure but I think the problem might lie in this function which is called in the `invokeResource` function in `coap-client.ts`:

https://github.com/eclipse/thingweb.node-wot/blob/8d48f0e934a304fbc2cd9084a55f1808143d5e26/packages/core/src/protocol-helpers.ts#L254-L271

Maybe there could be check added that asserts that the `stream` is not `undefined` and otherwise lets the function return an empty buffer (or `undefined`)?

**Comment by danielpeintner** [comment]
Thanks for the hint.
There were similar issues in the HTTP fixes for https://github.com/eclipse/thingweb.node-wot/pull/513

The question is whether `readStreamFully()` should be called if no response is expected. 
Anyhow, I will try to take a look.
