### ISSUE TITLE
Github labels for each binding/package

### ISSUE THREAD

**Issue by JKRhb** [eclipse/thingweb.node-wot#536]
At the moment, binding or package related issues are often prefixed with the package they are referring to. I wanted to suggest the introduction of binding/package specific labels which could be used instead/additionally to better keep track.

**Comment by danielpeintner** [comment]
There is one downside with labels. Only team members can associate a label. Anyhow, I think having labels makes sense.

I suggest to create the following labels.

* binding-coap
* binding-file
* binding-firestore
* binding-http
* binding-mbus 
* binding-modbus
* binding-mqtt
* binding-netconf
* binding-opcua
* binding-websockets 
* browser-bundle
* cli
* core
* td-tools 

No label since it is likely to go away soon (see https://github.com/eclipse/thingweb.node-wot/issues/508).
* binding-fujitsu
* binding-oracle

**Comment by relu91** [comment]
I did the fun part of defining the labels and tagging every issue 🤣 I hope everything got covered. Feel free to add missing labels or to label issues.

**Comment by JKRhb** [comment]
> I did the fun part of defining the labels and tagging every issue 🤣 I hope everything got covered. Feel free to add missing labels or to label issues.

Awesome! Thank you for this! :)
