### ISSUE TITLE
[core] Critical warning -  uuid@3.4.0

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#616]
`npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.`

`npm list uuid` shows

+-- @node-wot/core@0.8.0 -> .\packages\core
| `-- uuid@7.0.3
`-- nyc@15.1.0
  `-- istanbul-lib-processinfo@2.0.2
    `-- uuid@3.4.0

Hence it comes from "nyc" and we set it to latest "^15.1.0" version.
https://github.com/eclipse/thingweb.node-wot/blob/c2593cb38724874a826320ef00e7fa1d6dd8c7ca/package.json#L65

**Comment by JKRhb** [comment]
This seems to be a known issue over in the `istanbul-lib-processinfo` repository (see https://github.com/istanbuljs/istanbul-lib-processinfo/pull/21).

**Comment by relu91** [comment]
btw now the discussion has moved here: https://github.com/istanbuljs/istanbul-lib-processinfo/pull/22

**Comment by relu91** [comment]
My feeling is that it won't be fixed soon, since the maintainer is not active on GitHub for almost a year. (He also declared to have an off period [here](https://twitter.com/_coreyfarrell_/status/1380131753076068357). My suggestion is to look for alternatives, my understanding is that NYC is just a coverage library. Can't we use: https://github.com/bcoe/c8 or https://github.com/gotwarlost/istanbul ?
